<?php
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST');
if($_GET["keywords"]!=null)
{
$counter=0;
$ebayurl="http://svcs.eBay.com/services/search/FindingService/v1?siteid=0&SECURITY-APPNAME=USCeae99b-757b-429c-99b5-4281d1d9146&OPERATION-NAME=findItemsAdvanced&SERVICE-VERSION=1.0.0&RESPONSE-DATA-FORMAT=XML&keywords=";
$keywords = urlencode($_GET["keywords"]);
$keywords=preg_replace('/\s+/',"+",$keywords);
$ebayurl=$ebayurl.$keywords;
$ebayurl=$ebayurl."&paginationInput.entriesPerPage=";
$resultperpage=preg_replace('/\s+/',"+",$_GET["resultperpage"]);
$ebayurl=$ebayurl.$resultperpage;
$ebayurl=$ebayurl."&sortOrder=";
$sortby=preg_replace('/\s+/',"+",$_GET["sortby"]);
$ebayurl=$ebayurl.$sortby;
$ebayurl=$ebayurl."&paginationInput.pageNumber=";
$pagenumber=preg_replace('/\s+/',"+",$_GET["pagenumber"]);
$ebayurl=$ebayurl.$pagenumber;
$ebayurl=$ebayurl."&outputSelector(0)=SellerInfo&outputSelector(1)=StoreInfo&outputSelector(2)=PictureURLSuperSize";
if($_GET["from"]!=null)
{
$ebayurl=$ebayurl."&itemFilter($counter).name=MinPrice&itemFilter($counter).value=";
$MinPrice=preg_replace('/\s+/',"+",$_GET["from"]);
$ebayurl=$ebayurl.$MinPrice;
$counter++;
}
if($_GET["tofield"]!=null)
{
$ebayurl=$ebayurl."&itemFilter($counter).name=MaxPrice&itemFilter($counter).value=";
$MaxPrice=preg_replace('/\s+/',"+",$_GET["tofield"]);
$ebayurl=$ebayurl.$MaxPrice;
$counter++;
}
if(!empty($_GET['condition'])){
$condiationcounter=0;
$ebayurl=$ebayurl."&itemFilter($counter).name=Condition";
foreach($_GET['condition'] as $selected)
{
$ebayurl=$ebayurl."&itemFilter($counter).value[$condiationcounter]=";
$ebayurl=$ebayurl.$selected;
$condiationcounter++;
}
$counter++;
}
if(!empty($_GET['buyingformat'])){
$buyingformatcounter=0;
$ebayurl=$ebayurl."&itemFilter($counter).name=ListingType";
foreach($_GET['buyingformat'] as $selected)
{
$ebayurl=$ebayurl."&itemFilter($counter).value[$buyingformatcounter]=";
$ebayurl=$ebayurl.$selected;
$buyingformatcounter++;
}
$counter++;
}
$return= (isset($_GET['returnaccepted']));
if($return!=null)
{
$ebayurl=$ebayurl."&itemFilter($counter).name=ReturnsAcceptedOnly&itemFilter($counter).value=";
$ReturnAccepted=preg_replace('/\s+/',"+",$return);
$ebayurl=$ebayurl.$ReturnAccepted;
$counter++;
}
$freeshipping=(isset($_GET['FreeShippingOnly']));
if($freeshipping!=null)
{
$ebayurl=$ebayurl."&itemFilter($counter).name=FreeShippingOnly&itemFilter($counter).value=";
$FreeShippingOnly=preg_replace('/\s+/',"+",$freeshipping);
$ebayurl=$ebayurl.$FreeShippingOnly;
$counter++;
}
$expedited=(isset($_GET['ExpeditedShippingType']));
if($expedited!=null)
{
$ebayurl=$ebayurl."&itemFilter($counter).name=ExpeditedShippingType&itemFilter($counter).value=";
$ExpeditedShippingType="Expedited";
$ebayurl=$ebayurl.$ExpeditedShippingType;
$counter++;
}
if($_GET["MaxHandlingTime"]!=null)
{
$ebayurl=$ebayurl."&itemFilter($counter).name=MaxHandlingTime&itemFilter($counter).value=";
$MaxHandlingTime=preg_replace('/\s+/',"+",$_GET["MaxHandlingTime"]);
$ebayurl=$ebayurl.$MaxHandlingTime;
$counter++;
}
//echo("$ebayurl");
$xmlload=new SimpleXmlElement(file_get_contents($ebayurl));
if($xmlload->paginationOutput->totalEntries ==0)
{
$load='{"ack":"No results found"}';
echo ($load); 
}
else
{
//$keywordname=$_GET["keywords"];
$successmessage=$xmlload->ack;
$resultCount=$xmlload->paginationOutput->totalEntries;
$pageNumber=$xmlload->paginationOutput->pageNumber;
$itemCount=$xmlload->paginationOutput->entriesPerPage;
$load='{"ack":"' . $successmessage.'",';
$load.='"resultCount":"'.$resultCount.'",';
$load.='"pageNumber":"'.$pageNumber.'",';
$load.='"itemCount":"'.$itemCount.'"';
$itemcounter = 0;
foreach($xmlload->searchResult->item as $Item)
{
$load.=',"item'.$itemcounter.'":{"basicInfo":';
$itemcounter=$itemcounter+1;
if(!empty($Item->title))
{
$title=$Item->title;
}
else
{
$title="N/A";
}
if(!empty($Item->viewItemURL))
{
$viewItemURL=$Item->viewItemURL;
}
else
{
$viewItemURL="N/A";
}
if(!empty($Item->galleryURL))
{
$galleryURL=$Item->galleryURL;
}
else
{
$galleryURL="N/A";
}
if(!empty($Item->pictureURLSuperSize))
{
$pictureURLSuperSize=$Item->pictureURLSuperSize;
}
else
{
$pictureURLSuperSize="N/A";
}
if(!empty($Item->sellingStatus->convertedCurrentPrice))
{
$convertedCurrentPrice=$Item->sellingStatus->convertedCurrentPrice;
}
else
{
$convertedCurrentPrice="N/A";
}
if(!empty($Item->shippingInfo->shippingServiceCost))
{
$shippingServiceCost=$Item->shippingInfo->shippingServiceCost;
}
else
{
$shippingServiceCost="N/A";
}
if(!empty($Item->condition->conditionDisplayName))
{
$conditionDisplayName=$Item->condition->conditionDisplayName;
}
else
{
$conditionDisplayName="N/A";
}
if(!empty($Item->listingInfo->listingType)) 
{
$listingType=$Item->listingInfo->listingType;
}
else
{
$listingType="N/A";
}
if(!empty($Item->location))
{
$location=$Item->location;
}
else
{
$location="N/A";
}
if(!empty($Item->primaryCategory->categoryName))
{
$categoryName=$Item->primaryCategory->categoryName;
}
else
{
$categoryName="N/A";
}
if(!empty($Item->topRatedListing))
{
$topRatedListing=$Item->topRatedListing;
}
else
{
$topRatedListing="N/A";
}
$arrayBasicInfo =array(
"title"=>"$title",
"viewItemURL"=>"$viewItemURL",
"galleryURL"=>"$galleryURL",
"pictureURLSuperSize"=>"$pictureURLSuperSize",
"convertedCurrentPrice"=>"$convertedCurrentPrice",
"shippingServiceCost"=>"$shippingServiceCost",
"conditionDisplayName"=>"$conditionDisplayName",
"listingType"=>"$listingType",
"location"=>"$location",
"categoryName"=>"$categoryName",
"topRatedListing"=>"$topRatedListing",
);
$load.=json_encode($arrayBasicInfo);
$load.=',"sellerInfo":';
if(!empty($Item->sellerInfo->sellerUserName))
{
$sellerUserName=$Item->sellerInfo->sellerUserName;
}
else
{
$sellerUserName="N/A";
}
if(!empty($Item->sellerInfo->feedbackScore))
{
$feedbackScore=$Item->sellerInfo->feedbackScore;
}
else
{
$feedbackScore="N/A";
}
if(!empty($Item->sellerInfo->positiveFeedbackPercent))
{
$positiveFeedbackPercent=$Item->sellerInfo->positiveFeedbackPercent;
}
else
{
$positiveFeedbackPercent="N/A";
}
if(!empty($Item->sellerInfo->feedbackRatingStar))
{
$feedbackRatingStar=$Item->sellerInfo->feedbackRatingStar;
}
else
{
$feedbackRatingStar="N/A";
}
if(!empty($Item->sellerInfo->topRatedSeller))
{
$topRatedSeller=$Item->sellerInfo->topRatedSeller;
}
else
{
$topRatedSeller="N/A";
}
if(!empty($Item->storeInfo->storeName))
{
$storeName=$Item->storeInfo->storeName;
}
else
{
$storeName="N/A";
}
if(!empty($Item->storeInfo->storeURL))
{
$storeURL=$Item->storeInfo->storeURL;
}
else
{
$storeURL="N/A";
}
$sellerInfo =array(
"sellerUserName"=>"$sellerUserName",
"feedbackScore"=>"$feedbackScore",
"positiveFeedbackPercent"=>"$positiveFeedbackPercent",
"feedbackRatingStar"=>"$feedbackRatingStar",
"topRatedSeller"=>"$topRatedSeller",
"sellerStoreName"=>"$storeName",
"sellerStoreURL"=>"$storeURL",
);
$load.=json_encode($sellerInfo);
$load.=',"shippingInfo":';
if(!empty($Item->shippingInfo->shippingType))
{
$shippingType=$Item->shippingInfo->shippingType;
}
else
{
$shippingType="N/A";
}
if(!empty($Item->shippingInfo->shipToLocations))
{
$shipToLocations="";
foreach($Item->shippingInfo->shipToLocations as $shippingLoc){
$shipToLocations.=$shippingLoc.',';
}
$shipToLocations=rtrim($shipToLocations,",");
}
else
{
$shipToLocations="N/A";
}
if(!empty($Item->shippingInfo->expeditedShipping))
{
$expeditedShipping=$Item->shippingInfo->expeditedShipping;
}
else
{
$expeditedShipping="N/A";
}
if(!empty($Item->shippingInfo->oneDayShippingAvailable))
{
$oneDayShippingAvailable=$Item->shippingInfo->oneDayShippingAvailable;
}
else
{
$oneDayShippingAvailable="N/A";
}
if(!empty($Item->returnsAccepted))
{
$returnsAccepted=$Item->returnsAccepted;
}
else
{
$returnsAccepted="N/A";
}
if(!empty($Item->shippingInfo->handlingTime))
{
$handlingTime=$Item->shippingInfo->handlingTime;
}
else
{
$handlingTime="N/A";
}
$shippingInfo =array(
"shippingType"=>"$shippingType",
"shipToLocations"=>"$shipToLocations",
"expeditedShipping"=>"$expeditedShipping",
"oneDayShippingAvailable"=>"$oneDayShippingAvailable",
"returnsAccepted"=>"$returnsAccepted",
"handlingTime"=>"$handlingTime",
);
$load.=json_encode($shippingInfo);
$load.="}";	
}
$load.="}";
//$load = json_encode($load);
echo $load;
}
}
?>